### ISSUE TITLE
Add support for interactive threads

### ISSUE THREAD

**Issue by simsurace** [carstenbauer/ThreadPinning.jl#56]
Julia 1.9 will introduce an interactive thread pools. Maybe the interactive threads can be pinned to specific cores/cpu threads as well?

**Comment by carstenbauer** [comment]
Absolutely! Note that since these "interactive threads" aren't particularly special with respect to affinity, so you can already pin them right now:

```julia
julia> using ThreadPinning

julia> [getcpuid(i) for i in 1:Threads.maxthreadid()]
5-element Vector{Int64}:
 17
 12
 14
 16
 18

julia> for i in 1:Threads.maxthreadid()
           pinthread(i, i)
       end

julia> [getcpuid(i) for i in 1:Threads.maxthreadid()]
5-element Vector{Int64}:
 1
 2
 3
 4
 5
```

It'd still be nice to have "proper" support for the new threadpool feature in ThreadPinning.jl (in particular in `getcpuid(s)`, `pinthread(s)`, and `threadinfo`). I've already started with this (`@tspawnat` works and `threadinfo` has a premature `threadpool` option) but my short sprint was halfhearted at best.

If you're willing to, please open a PR! I'd be happy to help with comments and pointers.

**Comment by simsurace** [comment]
Funny you get 5 threads here. Any thoughts on [this question on Slack](https://julialang.slack.com/archives/C6A044SQH/p1675766750908629)?

**Comment by simsurace** [comment]
https://github.com/JuliaLang/julia/issues/48580

**Comment by carstenbauer** [comment]
@simsurace I've improved the thread pool support in ThreadPinning.jl a lot on the `main` branch. Among others, `threadinfo`, `pinthreads`, and `getcpuids` all have `threadpool` keyword arguments which can be set to `:default`, `:interactive`, or `:all`. Would be great if you could try this out, since I plan to tag a new release with this soon.

**Comment by simsurace** [comment]
I'll probably try this again quite soon, when https://github.com/JuliaLang/julia/pull/48702 has been released.
